spring:
    data:
      mongodb:
        host: 127.0.0.1
        port: 27017
        database: patient_db


billing:
  service:
       url: 'http://${billing.service.host}:${billing.service.port}/billing/pay'
       host: 127.0.0.1
       port: 9091