version: "3"

services:
  patient-service:
    image: patient-service:1.0
    container_name: patient-service
    ports:
    - 9090:9090
    restart: on-failure
    networks:
      - patient-mysql
      - patient-mongo
    depends_on:
      - mysql-db
      - mongo-db
    links:
      - mysql-db
      - mongo-db
  mysql-db:
    image: mysql:8
    container_name: mysql-db
    ports:
    - 3306:3306
    networks:
      - patient-mysql
    volumes:
      - 'mysqldata:/var/lib/mysql'
      - './init_scripts:/docker-entrypoint-initdb.d'
    environment:
      - MYSQL_ROOT_PASSWORD=14292
      - MYSQL_USER=root
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - 27017:27017
    networks:
      - patient-mongo
    volumes:
     - 'mongodata:/data/db'
     - './init_scripts:/docker-entrypoint-initdb.d' 
    environment:
     - MONGO_INITDB_ROOT_USERNAME=admin
     - MONGO_INITDB_ROOT_PASSWORD=14292
    restart: unless-stopped
    
networks:
  patient-mysql:
  patient-mongo:
  
volumes:
  mysqldata:
  mongodata:  