version: "3"

services:
  billing-service:
    image: billing-service:1.0
    container_name: billing_service
    ports:
    - 9091:9091
    restart: on-failure
    networks:
      - patient-visit-service_patient-mysql
      - patient-visit-service_patient-mongo
      - patient-visit-service_patient-billing
    depends_on:
      - mysql-db
      - mongo-db
    links:
      - mysql-db
      - mongo-db
  
    
networks:
   patient-visit-service_patient-mysql:
        external: true
   patient-visit-service_patient-mongo:
        external: true   
   patient-visit-service_patient-billing:
        external: true
   